version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: portfolio
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio
      MYSQL_PASSWORD: portfolio
    ports:
      - '3306:3306'
  web:
    image: php:7.2.2-apache
    container_name: php_web
    build: .
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
